version: "3.3"
services:
  backend-loadbalancer:
    build: ./loadbalancer/backend/
    ports:
      - "3000:80"
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
      - backend5
      - backend6
  backend1:
    build: ./todo-api/
    ports:
      - "3001:9000"
    environment:
      DATABASE_SERVER: "sql"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Eveling123*"
      DATABASE_OPTION_DATABASE: "TODOS"
      API_PORT: "9000"
      SERVER_TAG: "BACKEND 1"
    depends_on:
      - database
    links:
      - "database"
  backend2:
    build: ./todo-api/
    ports:
      - "3002:9000"
    environment:
      DATABASE_SERVER: "sql"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Eveling123*"
      DATABASE_OPTION_DATABASE: "TODOS"
      API_PORT: "9000"
      SERVER_TAG: "BACKEND 2"
    depends_on:
      - database
    links:
      - "database"
  backend3:
    build: ./todo-api/
    ports:
      - "3003:9000"
    environment:
      DATABASE_SERVER: "sql"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Eveling123*"
      DATABASE_OPTION_DATABASE: "TODOS"
      API_PORT: "9000"
      SERVER_TAG: "BACKEND 3"
    depends_on:
      - database
    links:
      - "database"
  backend4:
    build: ./todo-api/
    ports:
      - "3004:9000"
    environment:
      DATABASE_SERVER: "sql"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Eveling123*"
      DATABASE_OPTION_DATABASE: "TODOS"
      API_PORT: "9000"
      SERVER_TAG: "BACKEND 4"
    depends_on:
      - database
    links:
      - "database"
  backend5:
    build: ./todo-api/
    ports:
      - "3005:9000"
    environment:
      DATABASE_SERVER: "sql"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Eveling123*"
      DATABASE_OPTION_DATABASE: "TODOS"
      API_PORT: "9000"
      SERVER_TAG: "BACKEND 5"
    depends_on:
      - database
    links:
      - "database"
  backend6:
    build: ./todo-api/
    ports:
      - "3006:9000"
    environment:
      DATABASE_SERVER: "sql"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Eveling123*"
      DATABASE_OPTION_DATABASE: "TODOS"
      API_PORT: "9000"
      SERVER_TAG: "BACKEND 6"
    depends_on:
      - database
    links:
      - "database"
  database:
    image: "mcr.microsoft.com/mssql/server"
    user: "0:0"
    hostname: "sql"
    environment:
      SA_PASSWORD: "Eveling123*"
      ACCEPT_EULA: "Y"
    volumes:
      - info:/var/opt/mssql/data
volumes:
  info:
